# -*- coding: utf-8 -*-
"""TEXT_TO_IMAGE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jG8fN53nW94BqW4-r7pPjmEwmz41xK6u

NEW IMPLEMENTATION
"""

import torch
print(torch.cuda.is_available())

!pip install diffusers transformers accelerate safetensors
!pip install xformers
!pip install torch torchvision --upgrade

import torch
from diffusers import StableDiffusionPipeline

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16
)

pipe = pipe.to("cuda")
pipe.enable_xformers_memory_efficient_attention()
pipe.enable_attention_slicing()

prompt = "ultra realistic cyberpunk city at night, neon lights, 8k, highly detailed"

negative_prompt = "blurry, low quality, distorted"

image = pipe(
    prompt,
    negative_prompt=negative_prompt,
    num_inference_steps=25,
    guidance_scale=7.5
).images[0]

image

image.save("generated_image.png")

!pip install diffusers transformers accelerate

from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained(
    "SimianLuo/LCM_Dreamshaper_v7",
    torch_dtype=torch.float16
).to("cuda")

prompt = "realistic astronaut riding a horse on mars"

image = pipe(prompt, num_inference_steps=4).images[0]

image

from diffusers import DiffusionPipeline
import torch

# Load SDXL model
model_id = "stabilityai/stable-diffusion-xl-base-1.0"

pipe = DiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16"
)

pipe = pipe.to("cuda")

# Memory optimization
pipe.enable_xformers_memory_efficient_attention()
pipe.enable_attention_slicing()

# Prompt
prompt = """
A majestic white tiger walking through a dense jungle,
ultra realistic, 8k resolution, sharp focus, cinematic lighting,
detailed fur texture, depth of field, professional wildlife photography,
National Geographic style
"""

# Negative prompt
negative_prompt = """
blurry, low quality, low resolution, worst quality, distorted, deformed,
bad anatomy, extra limbs, extra legs, extra head, duplicate, cropped,
out of frame, watermark, text, logo, jpeg artifacts, oversaturated,
unrealistic colors, cartoon, painting, sketch, noise
"""

# Generate image
image = pipe(
    prompt=prompt,
    negative_prompt=negative_prompt,
    num_inference_steps=40,
    guidance_scale=7.5,
    height=768, # Lowering resolution to reduce memory usage
    width=768 # Lowering resolution to reduce memory usage
).images[0]

# Save image
image.save("white_tiger_jungle.png")

pip install diffusers transformers accelerate safetensors torch

from diffusers import StableDiffusionPipeline
import torch

# Load model (lighter model to avoid GPU memory issues)
model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16
)

pipe = pipe.to("cuda")

# Memory optimization
pipe.enable_attention_slicing()

# Universal negative prompt
negative_prompt = "blurry, low quality, distorted, watermark, text, logo, bad anatomy"

# 10 prompts
prompts = [
"A majestic white tiger walking through a dense jungle, ultra realistic, cinematic lighting, wildlife photography",

"A futuristic cyberpunk city at night with neon lights reflecting on wet streets, flying cars, ultra detailed",


"A huge medieval fantasy castle on top of a mountain, dramatic sky, cinematic lighting, ultra detailed",

"A colorful underwater coral reef with tropical fish swimming, sunlight rays through water",

"A peaceful lake surrounded by snow covered mountains during sunrise, ultra realistic landscape photography",

"A futuristic humanoid robot standing in a neon cyberpunk city, glowing blue circuits, ultra detailed metal",

"A red luxury sports car driving on a mountain road at sunset, cinematic lighting, ultra realistic",

"A massive spiral galaxy in deep space with glowing nebula clouds and billions of stars",

"A magical floating island with waterfalls and glowing trees, fantasy world, dramatic sunset lighting"
]

# Generate images
for i, prompt in enumerate(prompts):

    image = pipe(
        prompt=prompt,
        negative_prompt=negative_prompt,
        num_inference_steps=30,
        guidance_scale=7.5,
        height=512,
        width=512
    ).images[0]

    image.save(f"generated_image_{i+1}.png")
    print(f"Image {i+1} generated!")

print("All images generated successfully!")

from diffusers import DiffusionPipeline
import torch

model_id = "stabilityai/stable-diffusion-xl-base-1.0"

pipe = DiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16"
)

pipe.enable_model_cpu_offload()
pipe.enable_attention_slicing()

negative_prompt = """
blurry, low quality, low resolution, worst quality, distorted, deformed,
bad anatomy, cartoon, painting, sketch, watermark, text, logo
"""

prompts = [

"""A photorealistic arctic wolf standing on a snowy mountain during sunrise,
ultra realistic wildlife photography, sharp focus, cinematic lighting,
National Geographic style""",

"""A busy street market in Tokyo at night with glowing lanterns and neon signs,
photorealistic photography, ultra detailed environment, cinematic lighting""",

"""A caravan of camels walking across a vast desert during golden sunset,
photorealistic landscape photography, dramatic sky, cinematic lighting""",

"""A rainy city street at night with reflections of colorful neon lights
on wet roads, photorealistic urban photography, cinematic atmosphere""",

"""A small wooden cabin in a snowy forest with warm light glowing from windows,
photorealistic winter landscape, soft cinematic lighting""",

"""A peaceful mountain village surrounded by green hills and rivers,
photorealistic landscape photography, morning sunlight, ultra detailed""",

"""A photorealistic eagle flying above a deep canyon during sunset,
ultra detailed feathers, wildlife photography, cinematic lighting""",

"""A tall lighthouse standing on a rocky ocean coast during a storm,
huge waves crashing, photorealistic seascape photography""",

"""A futuristic city highway with glowing electric cars at night,
ultra realistic architecture photography, neon reflections""",


]

for i, prompt in enumerate(prompts):

    image = pipe(
        prompt=prompt,
        negative_prompt=negative_prompt,
        num_inference_steps=30,
        guidance_scale=7.5,
        height=512,
        width=512
    ).images[0]

    image.save(f"realistic_image_{i+1}.png")

    torch.cuda.empty_cache()

print("All 10 realistic images generated successfully!")

from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained(
    "SimianLuo/LCM_Dreamshaper_v7",
    torch_dtype=torch.float16
).to("cuda")

prompts = [



"realistic futuristic cyberpunk city at night, neon lights reflecting on wet streets, ultra detailed buildings",

"photorealistic golden retriever running in green grass field during sunset, detailed fur, DSLR photography",

"ultra realistic waterfall in tropical rainforest, sunlight rays through trees, highly detailed nature photography",

"realistic lion standing in African savannah during golden sunset, ultra detailed fur, National Geographic style",

"photorealistic snowy mountain lake during sunrise with reflection in water, ultra detailed landscape photography",

"realistic luxury red sports car on mountain road during sunset, cinematic lighting, automotive photography",

"photorealistic underwater coral reef with colorful fish swimming, sun rays through water, ultra detailed",

"realistic medieval castle on mountain cliff during sunrise, dramatic clouds, cinematic lighting, ultra detailed fantasy architecture"
]

for i, prompt in enumerate(prompts):

    image = pipe(
        prompt,
        num_inference_steps=6,   # slightly higher for better detail
        guidance_scale=1.5
    ).images[0]

    image.save(f"image_{i+1}.png")

print("10 detailed images generated successfully")

from diffusers import DiffusionPipeline
import torch

model_id = "stabilityai/stable-diffusion-xl-base-1.0"

pipe = DiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16"
)

pipe.enable_model_cpu_offload()
pipe.enable_attention_slicing()

negative_prompt = """
blurry, low quality, low resolution, worst quality, distorted, deformed,
bad anatomy, cartoon, painting, sketch, watermark, text, logo
"""

prompts = [

"""A realistic polar bear walking on Arctic ice during sunrise,
ultra detailed fur, wildlife photography, cinematic lighting""",

"""A vibrant Indian street food market at night with colorful lights,
photorealistic environment, detailed crowd and food stalls""",

"""A dramatic thunderstorm over a mountain valley,
dark clouds, lightning strikes, ultra realistic nature photography""",

"""A modern futuristic smart city skyline at sunset,
glass skyscrapers reflecting sunlight, ultra realistic architecture photography""",

"""A realistic astronaut floating in space near the International Space Station,
Earth visible in the background, ultra detailed NASA photography style""",

"""A luxury yacht sailing in crystal blue ocean water during sunset,
photorealistic travel photography, cinematic lighting""",

"""A realistic elephant walking through African savannah grasslands,
golden sunset lighting, National Geographic wildlife photography""",

"""A cozy coffee shop interior with warm lighting and wooden furniture,
photorealistic interior photography, shallow depth of field""",

"""A high-speed bullet train passing through snowy mountains,
ultra realistic transportation photography, dramatic lighting""",

"""A vibrant underwater scene with dolphins swimming in clear blue ocean,
photorealistic underwater photography with sunlight rays"""
]

for i, prompt in enumerate(prompts):

    image = pipe(
        prompt=prompt,
        negative_prompt=negative_prompt,
        num_inference_steps=30,
        guidance_scale=7.5,
        height=512,
        width=512
    ).images[0]

    image.save(f"generated_image_{i+1}.png")

    torch.cuda.empty_cache()

print("All 10 images generated successfully!")

"""FINAL IMPLEMENTATION OF THE PROJECT:

TEXT TO IMAGE GENERATION USING DIFFUSION MODEL **bold text**
"""

# Check if CUDA-enabled GPU is available for PyTorch computations
import torch
print(torch.cuda.is_available())

# Install all required libraries for Stable Diffusion including diffusers, transformers, accelerate, safetensors, xformers, and the latest version of PyTorch

!pip install diffusers transformers accelerate safetensors
!pip install xformers
!pip install torch torchvision --upgrade

# Import the required libraries: PyTorch for tensor computation and StableDiffusionPipeline from diffusers for text-to-image generation

import torch
from diffusers import StableDiffusionPipeline

#Install Required Libraries
!pip install -q diffusers transformers accelerate safetensors
!pip install -q xformers

#Import Libraries
import torch
from diffusers import StableDiffusionPipeline

"""The system uses the Stable Diffusion v1.5 model (runwayml/stable-diffusion-v1-5),
a Latent Diffusion Model designed for text-to-image generation. The model
operates at a native resolution of 512×512 and utilizes a CLIP text encoder
to convert natural language prompts into latent representations used for
image synthesis.
"""

# ============================================================
# Model Details
# ============================================================

# Model Name      : Stable Diffusion v1.5
# HuggingFace ID  : runwayml/stable-diffusion-v1-5
# Model Type      : Text-to-Image Diffusion Model
# Native Resolution: 512 x 512
# Architecture    : Latent Diffusion Model (LDM)
# Text Encoder    : CLIP (Contrastive Language Image Pretraining)

# ============================================================
# Install Required Libraries (Run in Google Colab)
# ============================================================

!pip install -q diffusers transformers accelerate safetensors xformers

# ============================================================
# Import Libraries
# ============================================================

import torch
from diffusers import StableDiffusionPipeline

# ============================================================
# Load Stable Diffusion Model
# ============================================================

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    safety_checker=None
)

# Move model to GPU
pipe = pipe.to("cuda")

# Enable memory optimization
pipe.enable_attention_slicing()

# Enable xformers if available
try:
    pipe.enable_xformers_memory_efficient_attention()
except:
    print("xformers not installed, running without it")

# ============================================================
# Text Prompt for Image Generation
# ============================================================

prompt = "Ultra realistic portrait of a cyberpunk girl wearing neon glasses, cinematic lighting, 8k, highly detailed"

negative_prompt = """
blurry, low quality, distorted, bad anatomy,
extra limbs, worst quality
"""

# ============================================================
# Generate Image
# ============================================================

image = pipe(
    prompt=prompt,
    negative_prompt=negative_prompt,
    height=512,
    width=512,
    num_inference_steps=30,
    guidance_scale=7.5
).images[0]

# ============================================================
# Display Image
# ============================================================

image

!pip install -q diffusers transformers accelerate safetensors xformers

# ============================================================
# Import Libraries
# ============================================================

import torch
from diffusers import StableDiffusionPipeline

# ============================================================
# Load Model
# ============================================================

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    safety_checker=None
)

pipe = pipe.to("cuda")

pipe.enable_attention_slicing()

try:
    pipe.enable_xformers_memory_efficient_attention()
except:
    print("xformers not available")

# ============================================================
# Prompts (3 different prompts)
# ============================================================

prompts = [


    "A futuristic smart city with flying cars, neon lights, cyberpunk style, ultra realistic, 8k",

    "An astronaut sitting on the moon drinking coffee while looking at Earth, ultra realistic, space photography, high detail",

    "A cute baby panda sitting in a bamboo forest eating bamboo, wildlife photography, soft lighting, highly detailed"
]

negative_prompt = """
blurry, low quality, distorted, bad anatomy,
extra limbs, worst quality
"""

# ============================================================
# Generate Images for Each Prompt
# ============================================================

for i, prompt in enumerate(prompts):

    image = pipe(
        prompt=prompt,
        negative_prompt=negative_prompt,
        height=512,
        width=512,
        num_inference_steps=30,
        guidance_scale=7.5
    ).images[0]

    # Show image
    display(image)

    # Save image
    image.save(f"generated_image_{i+1}.png")

# Install the required libraries (diffusers, transformers, and accelerate) needed to run the Stable Diffusion text-to-image model

!pip install diffusers transformers accelerate

"""Model Details

Model Name: LCM Dreamshaper v7

Hugging Face ID: SimianLuo/LCM_Dreamshaper_v7

Model Type: Text-to-Image Diffusion Model

Architecture: Latent Consistency Model (LCM)

Base Model: DreamShaper v7 (Fine-tuned Stable Diffusion)

Native Resolution: 512 × 512

Text Encoder: CLIP (Contrastive Language Image Pretraining)

Main Feature:
This model is optimized for very fast image generation using Latent Consistency Models.
Unlike traditional Stable Diffusion models that require 25–50 inference steps, this model
can generate high-quality images using only 2–8 inference steps.
"""

# Import DiffusionPipeline and PyTorch, load the LCM Dreamshaper v7 model for fast image generation on GPU,
# define a text prompt, and generate an image using a small number of inference steps

from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained(
    "SimianLuo/LCM_Dreamshaper_v7",
    torch_dtype=torch.float16
).to("cuda")

prompt = "realistic astronaut riding a horse on mars"

image = pipe(prompt, num_inference_steps=4).images[0]

image

# Import DiffusionPipeline and PyTorch
from diffusers import DiffusionPipeline
import torch

# Load LCM Dreamshaper v7 model
pipe = DiffusionPipeline.from_pretrained(
    "SimianLuo/LCM_Dreamshaper_v7",
    torch_dtype=torch.float16
).to("cuda")

# Updated prompts
prompts = [
    "a majestic white tiger walking in a snowy forest, ultra realistic wildlife photography, highly detailed",
    "a futuristic robot standing in a neon cyberpunk street at night, cinematic lighting, ultra detailed",
    "a cute golden retriever puppy playing in a sunflower field, bright sunlight, highly detailed"
]

# Generate images
for prompt in prompts:
    image = pipe(prompt, num_inference_steps=4).images[0]
    display(image)

# Import required libraries and load the LCM Dreamshaper model for fast image generation

from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained(
    "SimianLuo/LCM_Dreamshaper_v7",
    torch_dtype=torch.float16
).to("cuda")

# Define prompt and negative prompt for better face quality
prompt = "ultra realistic astronaut riding a horse on mars, detailed human face, cinematic lighting, 8k, highly detailed, photorealistic"

negative_prompt = "blurry, low quality, distorted face, extra fingers, deformed face"

# Generate image with better quality settings
image = pipe(
    prompt,
    negative_prompt=negative_prompt,
    num_inference_steps=8,
    guidance_scale=7
).images[0]

image

"""Model Details

Model Name: Stable Diffusion XL (SDXL)

Hugging Face Model ID: stabilityai/stable-diffusion-xl-base-1.0

Model Type: Text-to-Image Diffusion Model

Architecture: Latent Diffusion Model (LDM)

Developer: Stability AI

Native Resolution: 1024 × 1024 pixels (high-resolution generation)

Text Encoder: CLIP-based dual text encoders

Description:
Stable Diffusion XL (SDXL) is an advanced text-to-image generation model
developed by Stability AI. It produces high-quality and highly detailed
images from natural language prompts. SDXL improves prompt understanding,
image realism, and composition compared to earlier Stable Diffusion models.




"""

# Import required libraries
from diffusers import DiffusionPipeline
import torch

# Load Stable Diffusion XL base model
model_id = "stabilityai/stable-diffusion-xl-base-1.0"

pipe = DiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16"
)

# Move model to GPU
pipe = pipe.to("cuda")

# Memory optimization
pipe.enable_attention_slicing()

try:
    pipe.enable_xformers_memory_efficient_attention()
except:
    print("xformers not installed, running without it")

# Prompt
prompt = """
Ultra realistic wildlife photography of a majestic white tiger walking
through a dense jungle, detailed fur texture, cinematic lighting,
sharp focus, depth of field, 8k resolution, National Geographic style
"""

# Negative prompt
negative_prompt = """
blurry, low quality, low resolution, distorted, deformed, bad anatomy,
extra limbs, duplicate, cropped, watermark, text, logo, jpeg artifacts,
cartoon, painting, sketch, oversaturated colors
"""

# Generate image
image = pipe(
    prompt=prompt,
    negative_prompt=negative_prompt,
    num_inference_steps=30,
    guidance_scale=7.5,
    height=768,
    width=768
).images[0]

# Display image
image

# Save image as JPG
image.save("photo1.jpg")

# Import required libraries
from diffusers import DiffusionPipeline
import torch

# Load Stable Diffusion XL model
model_id = "stabilityai/stable-diffusion-xl-base-1.0"

pipe = DiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16"
)

# Move model to GPU
pipe = pipe.to("cuda")

# Memory optimization
pipe.enable_attention_slicing()

try:
    pipe.enable_xformers_memory_efficient_attention()
except:
    print("xformers not installed")

# Negative prompt
negative_prompt = """
blurry, low quality, distorted, bad anatomy, extra limbs,
duplicate, watermark, text, logo, jpeg artifacts
"""

# 10 different prompts
prompts = [

"Ultra realistic portrait of a young woman, DSLR photography, natural skin texture, soft lighting, 8k",

"A majestic white tiger walking through dense jungle, wildlife photography, cinematic lighting, ultra detailed",

"A futuristic cyberpunk city at night with neon lights and flying cars, ultra realistic, 8k resolution",

"A luxury red sports car parked on a mountain road during sunset, cinematic lighting, photorealistic",

"A cute golden retriever puppy playing in a sunflower field, bright sunlight, highly detailed",

"An astronaut standing on the moon looking at Earth, space photography, ultra realistic",

"A magical fantasy castle floating in the sky above clouds, dramatic lighting, ultra detailed",

"A modern smart city with advanced technology and green buildings, futuristic architecture",

"A beautiful waterfall in a tropical rainforest with mist and sunlight, nature photography",

"A robotic humanoid standing in a neon cyberpunk street, cinematic lighting, ultra realistic"
]

# Generate images
for i, prompt in enumerate(prompts):

    image = pipe(
        prompt=prompt,
        negative_prompt=negative_prompt,
        num_inference_steps=30,
        guidance_scale=7.5,
        height=768,
        width=768
    ).images[0]

    # Show image
    display(image)

    # Save image
    image.save(f"photo{i+1}.jpg")

# Install the required Python libraries such as diffusers, transformers, accelerate, safetensors, and torch to run Stable Diffusion models for text-to-image generation

!pip install diffusers transformers accelerate safetensors torch

"""Model Details

Model Name: Stable Diffusion v1.5

Hugging Face Model ID: runwayml/stable-diffusion-v1-5

Model Type: Text-to-Image Diffusion Model

Architecture: Latent Diffusion Model (LDM)

Developer: Runway ML in collaboration with Stability AI

Native Resolution: 512 × 512 pixels

Text Encoder: CLIP (Contrastive Language–Image Pretraining)

Description:
Stable Diffusion v1.5 is a widely used open-source text-to-image generation
model that converts natural language prompts into images. It uses a latent
diffusion architecture where the model generates images in a compressed
latent space and then decodes them into full-resolution images.
"""

# Import the Stable Diffusion pipeline and PyTorch
from diffusers import StableDiffusionPipeline
import torch

# Load Stable Diffusion v1.5 model
model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16
)

pipe = pipe.to("cuda")

# Memory optimization
pipe.enable_attention_slicing()

# Universal negative prompt
negative_prompt = "blurry, low quality, distorted, watermark, text, logo, bad anatomy"

# 10 unique prompts
prompts = [

"A glowing bioluminescent forest at night with giant mushrooms and magical fireflies, fantasy environment, ultra detailed",

"A futuristic floating city above the clouds with flying vehicles and glass skyscrapers, sci-fi architecture",

"A giant ancient tree with houses built inside it, fantasy village, warm sunset lighting",

"A steampunk airship flying above a Victorian city with smoke and gears, cinematic lighting",

"A crystal cave glowing with blue and purple minerals, reflections on water, ultra detailed environment",

"A peaceful Japanese temple surrounded by cherry blossom trees during spring, traditional architecture",

"A desert caravan traveling across golden sand dunes during sunset, cinematic wide landscape",

"A massive dragon sleeping on top of a mountain of gold inside a dark cave, fantasy art",

"A futuristic underwater research station surrounded by glowing jellyfish and deep sea creatures",

"A beautiful northern lights sky above a frozen Arctic landscape with snow covered mountains"
]

# Generate images
for i, prompt in enumerate(prompts):

    image = pipe(
        prompt=prompt,
        negative_prompt=negative_prompt,
        num_inference_steps=30,
        guidance_scale=7.5,
        height=512,
        width=512
    ).images[0]

    image.save(f"photo_image_{i+1}.png")
    print(f"Image {i+1} generated!")

print("All images generated successfully!")

# Import libraries
from diffusers import StableDiffusionPipeline
import torch
from IPython.display import display

# Load Stable Diffusion v1.5 model
model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16
)

pipe = pipe.to("cuda")

# Memory optimization
pipe.enable_attention_slicing()

# Negative prompt
negative_prompt = "blurry, low quality, distorted, watermark, text, logo, bad anatomy"

# 10 unique prompts
prompts = [

"A glowing bioluminescent forest at night with giant mushrooms and magical fireflies, fantasy environment",

"A futuristic floating city above the clouds with flying vehicles and glass skyscrapers",

"A giant ancient tree with houses built inside it, fantasy village with warm sunset lighting",

"A steampunk airship flying above a Victorian city with smoke and mechanical gears",

"A crystal cave glowing with blue and purple minerals with reflections on water",

"A peaceful Japanese temple surrounded by cherry blossom trees during spring",

"A desert caravan traveling across golden sand dunes during sunset",

"A massive dragon sleeping on a mountain of gold inside a dark cave",

"A futuristic underwater research station surrounded by glowing jellyfish",

"Northern lights above a frozen Arctic landscape with snow covered mountains"
]

# Generate and display images
for i, prompt in enumerate(prompts):

    image = pipe(
        prompt=prompt,
        negative_prompt=negative_prompt,
        num_inference_steps=30,
        guidance_scale=7.5,
        height=512,
        width=512
    ).images[0]

    print(f"Image {i+1}")
    display(image)

print("All images generated successfully!")

"""Model Details

Model Name: Stable Diffusion XL (SDXL)

Hugging Face Model ID: stabilityai/stable-diffusion-xl-base-1.0

Model Type: Text-to-Image Diffusion Model

Architecture: Latent Diffusion Model (LDM)

Developer: Stability AI

Native Resolution: 1024 × 1024 pixels

Text Encoder: Dual CLIP Text Encoders

Description:
Stable Diffusion XL (SDXL) is an advanced text-to-image generation model
developed by Stability AI. It produces highly detailed and realistic images
from natural language prompts. Compared to earlier Stable Diffusion models,
SDXL improves prompt understanding, lighting, textures, and overall image
composition.
"""

# Import DiffusionPipeline and PyTorch
from diffusers import DiffusionPipeline
import torch
from IPython.display import display

# Load Stable Diffusion XL model
model_id = "stabilityai/stable-diffusion-xl-base-1.0"

pipe = DiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16"
)

pipe.enable_model_cpu_offload()
pipe.enable_attention_slicing()

# Negative prompt
negative_prompt = """
blurry, low quality, distorted, deformed, bad anatomy,
cartoon, painting, sketch, watermark, text, logo
"""

# 10 different prompts
prompts = [

"A photorealistic polar bear walking across Arctic ice during sunset, cinematic wildlife photography",

"A futuristic floating city above the clouds with glass skyscrapers and flying vehicles",

"A magical glowing forest at night filled with fireflies and giant mushrooms, fantasy environment",

"A luxury yacht sailing across a turquoise tropical ocean during sunset, cinematic photography",

"A futuristic humanoid robot walking through a neon cyberpunk street at night",

"A beautiful waterfall inside a tropical rainforest with sunlight rays through mist",

"A traditional Japanese temple surrounded by cherry blossoms during spring",

"A red Ferrari sports car parked on a mountain road during golden sunset",

"A massive spiral galaxy with glowing nebula clouds and billions of stars in deep space",

"A medieval knight standing in armor in front of a giant castle during sunrise"
]

# Generate and display images
for i, prompt in enumerate(prompts):

    image = pipe(
        prompt=prompt,
        negative_prompt=negative_prompt,
        num_inference_steps=30,
        guidance_scale=7.5,
        height=512,
        width=512
    ).images[0]

    print(f"Image {i+1}")
    display(image)

    torch.cuda.empty_cache()

print("All images generated successfully!")

from google.colab import drive
drive.mount('/content/drive')

# Import DiffusionPipeline and PyTorch, load the Stable Diffusion XL model,
# enable CPU offloading and attention slicing to reduce GPU memory usage,
# define a set of realistic prompts and a negative prompt to avoid low-quality results,
# generate images for each prompt, save them automatically, and clear GPU memory after each generation.

from diffusers import DiffusionPipeline
import torch

model_id = "stabilityai/stable-diffusion-xl-base-1.0"

pipe = DiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16"
)

pipe.enable_model_cpu_offload()
pipe.enable_attention_slicing()

negative_prompt = """
blurry, low quality, low resolution, worst quality, distorted, deformed,
bad anatomy, cartoon, painting, sketch, watermark, text, logo
"""

prompts = [

"""A realistic polar bear walking on Arctic ice during sunrise,
ultra detailed fur, wildlife photography, cinematic lighting""",

"""A vibrant Indian street food market at night with colorful lights,
photorealistic environment, detailed crowd and food stalls""",

"""A dramatic thunderstorm over a mountain valley,
dark clouds, lightning strikes, ultra realistic nature photography""",

"""A modern futuristic smart city skyline at sunset,
glass skyscrapers reflecting sunlight, ultra realistic architecture photography""",

"""A realistic astronaut floating in space near the International Space Station,
Earth visible in the background, ultra detailed NASA photography style""",

"""A luxury yacht sailing in crystal blue ocean water during sunset,
photorealistic travel photography, cinematic lighting""",

"""A realistic elephant walking through African savannah grasslands,
golden sunset lighting, National Geographic wildlife photography""",

"""A cozy coffee shop interior with warm lighting and wooden furniture,
photorealistic interior photography, shallow depth of field""",

"""A high-speed bullet train passing through snowy mountains,
ultra realistic transportation photography, dramatic lighting""",

"""A vibrant underwater scene with dolphins swimming in clear blue ocean,
photorealistic underwater photography with sunlight rays"""
]

for i, prompt in enumerate(prompts):

    image = pipe(
        prompt=prompt,
        negative_prompt=negative_prompt,
        num_inference_steps=30,
        guidance_scale=7.5,
        height=512,
        width=512
    ).images[0]

    image.save(f"generated_image_{i+1}.png")

    torch.cuda.empty_cache()

print("All 10 images generated successfully!")